
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-fpm-container
    volumes:
      - .:/var/www/html
    environment:
      # Настройки окружения PHP
      APP_ENV: dev
      DATABASE_URL: postgres://app:pass@database:5432/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
    depends_on:
      - php-fpm
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

